/**
 * Created by patryk.witkowski_bri on 4/29/2025.
 */

public class Utils {
    public static PriceBookConstants PRICE_BOOK { get { return new PriceBookConstants(); } }
    public static OrderConstants ORDER { get { return new OrderConstants(); } }
    public static DiscountConstants DISCOUNT { get { return new DiscountConstants(); } }
    public static OpportunityConstants OPPORTUNITY { get { return new OpportunityConstants(); } }
    public static LogConstants LOG { get { return new LogConstants(); } }
    public static ProductConstants PRODUCT { get { return new ProductConstants(); } }
    public static CaseConstants CASES { get { return new CaseConstants(); } }
    public static CaseProductConstants CASE_PRODUCT { get { return new CaseProductConstants(); } }
}